apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-productinfo-server
  name: productinfo-server
spec:
  selector:
    app: grpc-productinfo-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 50051
      name: grpc-http
    - port: 443
      protocol: TCP
      targetPort: 50051
      name: grpc-https
    - port: 50051
      protocol: TCP
      targetPort: 50051
      name: grpc
  type: NodePort
